import { Category, MenuItem } from './types';

export const MENU_ITEMS: MenuItem[] = [
  {
    id: '1',
    name: 'Chicken Tikka Ultimate Cheese Pizza',
    description: 'Pizza topped with succulent chicken tikka pieces, red onions, and generous melted cheese. A perfect blend of flavors!',
    price: 434,
    category: Category.MAINS,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=300&fit=crop',
    isTopPick: true,
    rating: 4.5,
    reviewCount: 342,
  },
  {
    id: '2',
    name: 'Tandoori Paneer Ultimate Cheese Pizza',
    description: 'Serves 1 | Spiced paneer, crunchy onions & green capsicum, spicy red paprika with delicious tandoori sauce and mozzarella cheese.',
    price: 374,
    category: Category.MAINS,
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&h=300&fit=crop',
    isVegetarian: true,
    isTopPick: true,
    isBestseller: true,
    rating: 4.2,
    reviewCount: 198,
  },
  {
    id: '3',
    name: 'Triple Chicken Ultimate Cheese Pizza',
    description: 'Triple the chicken, triple the cheese! Loaded with chicken tikka, grilled chicken, and chicken sausage.',
    price: 454,
    category: Category.MAINS,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&h=300&fit=crop',
    isTopPick: true,
    rating: 4.3,
    reviewCount: 267,
  },
  {
    id: '4',
    name: 'Margherita',
    description: 'Pizza topped with our herb-infused signature pan sauce and mozzarella cheese. A classic treat for all cheese lovers out there!',
    price: 169,
    category: Category.MAINS,
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&h=300&fit=crop',
    isVegetarian: true,
    isBestseller: true,
    rating: 4.0,
    reviewCount: 255,
  },
  {
    id: '5',
    name: 'Veggie Feast',
    description: 'Serves 1 | Herbed onion and green capsicum, juicy sweet corn & mozzarella cheese with flavourful pan sauce.',
    price: 259,
    category: Category.MAINS,
    image: 'https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?w=400&h=300&fit=crop',
    isVegetarian: true,
    rating: 3.6,
    reviewCount: 131,
  },
  {
    id: '6',
    name: 'Tandoori Paneer',
    description: 'Serves 1 | It\'s our signature. Spiced paneer, crunchy onions & green capsicum, spicy red paprika with delicious tandoori sauce and mozzarella cheese.',
    price: 299,
    category: Category.MAINS,
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&h=300&fit=crop',
    isVegetarian: true,
    rating: 4.2,
    reviewCount: 198,
  },
  {
    id: '7',
    name: 'Farmhouse Pizza',
    description: 'Loaded with fresh vegetables, bell peppers, onions, tomatoes, and mozzarella cheese.',
    price: 279,
    category: Category.MAINS,
    image: 'https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?w=400&h=300&fit=crop',
    isVegetarian: true,
    rating: 4.1,
    reviewCount: 189,
  },
  {
    id: '8',
    name: 'Pepperoni Pizza',
    description: 'Classic pepperoni with mozzarella cheese and our signature tomato sauce.',
    price: 329,
    category: Category.MAINS,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&h=300&fit=crop',
    rating: 4.4,
    reviewCount: 312,
  },
  {
    id: '9',
    name: 'BBQ Chicken Pizza',
    description: 'Tender BBQ chicken with red onions, bell peppers, and mozzarella cheese.',
    price: 389,
    category: Category.MAINS,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=300&fit=crop',
    rating: 4.3,
    reviewCount: 245,
  },
  {
    id: '10',
    name: 'Cheese Burst Pizza',
    description: 'Double cheese burst with mozzarella and cheddar cheese. Pure cheesy delight!',
    price: 249,
    category: Category.MAINS,
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&h=300&fit=crop',
    isVegetarian: true,
    rating: 4.0,
    reviewCount: 178,
  },
];

export const TABLES = ['1', '2', '3', '4', '5', '6', 'VIP-1', 'OUTDOOR-1'];